#!/bin/bash

./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0500tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0501tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0502tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0503tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0504tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0505tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0506tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0507tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0508tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0509tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0510tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0511tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0512tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0513tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0514tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0515tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0516tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0517tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0518tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0519tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0520tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0521tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0522tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0523tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0524tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0525tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0526tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0527tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0528tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0529tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0530tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0531tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0532tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0533tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0534tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0535tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0536tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0537tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0538tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0539tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0540tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0541tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0542tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0543tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0544tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0545tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0546tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0547tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgiosPawlosbeiAgiosIonnis6Mai2013__DSC0549tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0001tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0002tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0003tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0004tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0005tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0007tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0008tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0009tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0010tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0011tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0012tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0013tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0014tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0015tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0016tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0017tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0018tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0019tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0020tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0021tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0022tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0023tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0024tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0025tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0026tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0027tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0028tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0029tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0030tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0031tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0032tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0033tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0034tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0035tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0037tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0038tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0039tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0040tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0041tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0042tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0043tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0044tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0045tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0046tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0047tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0048tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0049tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0050tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0051tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0052tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0053tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAgPanteleimonbeiPigi2Mai2013Fertig__DSC0054tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAlikambosPanagiaKapelleKoimesisKirche__DSC0478tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAlikambosPanagiaKapelleKoimesisKirche__DSC0479tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAlikambosPanagiaKapelleKoimesisKirche__DSC0480tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAlikambosPanagiaKapelleKoimesisKirche__DSC0481tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAlikambosPanagiaKapelleKoimesisKirche__DSC0482tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAlikambosPanagiaKapelleKoimesisKirche__DSC0483tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAlikambosPanagiaKapelleKoimesisKirche__DSC0484tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAlikambosPanagiaKapelleKoimesisKirche__DSC0485tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAlikambosPanagiaKapelleKoimesisKirche__DSC0486tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBAlikambosPanagiaKapelleKoimesisKirche__DSC0487tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBdasHaupttordesFortezzas__DSC0252tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBdasHaupttordesFortezzas__DSC0253tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBdasHaupttordesFortezzas__DSC0254tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBdasHaupttordesFortezzas__DSC0255tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBDasPortaldesRenierPalastes__DSC0488tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBDasPortaldesRenierPalastes__DSC0489tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBDasPortaldesRenierPalastes__DSC0490tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0153tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0154tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0155tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0156tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0157tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0158tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0159tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0160tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0161tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0162tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0163tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0164tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0165tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0166tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0167tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0168tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0169tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0170tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0171tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBEpiskopibeiVassilikiAgiiApostoliKirche3Mai2013FERTIG__DSC0172tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0550tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0551tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0552tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0553tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0554tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0555tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0556tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0557tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0558tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0560tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0561tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0562tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0563tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0564tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0565tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0566tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0567tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0568tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0569tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0570tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0571tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0572tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0573tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0574tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0575tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0576tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0577tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0578tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0579tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0580tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0581tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0582tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0583tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0584tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0585tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0586tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0587tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0588tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0589tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0590tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0591tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0592tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0593tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0594tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0595tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0596tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0597tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0598tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0599tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0600tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0601tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0602tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0603tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0604tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0605tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0606tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0607tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0608tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0609tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0610tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0611tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0612tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0613tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0614tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0615tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0616tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0620tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0621tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0622tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0623tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0624tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0625tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0626tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0627tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0628tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0629tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0630tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0631tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0632tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0633tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0634tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0635tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0636tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0637tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0638tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0639tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0640tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0641tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0642tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0643tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0644tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0645tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0646tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0647tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0650tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0651tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0652tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0653tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0654tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0655tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0657tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0658tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0659tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0660tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0661tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0662tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0663tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0664tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0665tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0706tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0710tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0711tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBFodelePanagiaLoumbiniesKirche__DSC0712tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0173tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0174tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0175tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0176tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0177tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0178tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0179tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0180tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0181tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0182tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0183tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0184tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0185tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0186tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0187tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0188tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0189tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0190tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0191tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0192tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0193tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0194tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0195tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0196tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0197tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0198tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0199tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0200tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0201tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0202tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0203tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0204tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0205tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0206tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0207tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0208tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0209tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0210tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0211tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0212tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0213tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBKaraMusaPaschaCamiiFertig__DSC0214tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0055tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0056tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0057tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0058tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0059tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0060tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0061tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0062tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0063tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0064tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0065tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0066tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0067tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0068tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0069tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0070tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0072tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0073tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0074tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0075tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0076tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0077tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0078tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0079tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0081tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0085tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0086tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0087tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0088tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0090tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0091tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0092tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniPanagiaKeraKardiotissa2Mai2013Fertig__DSC0093tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100321JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100322JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100324JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100325JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100326JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100327JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100328JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100329JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100330JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100331JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100332JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100333JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100334JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100335JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100336JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100337JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100338JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100339JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100340JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100341JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoniVrondisiou_SV100342JPG -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0256tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0257tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0259tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0260tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0261tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0262tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0263tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0264tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0265tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0266tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0267tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0268tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0269tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0270tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0271tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0272tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0273tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0274tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0275tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0276tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0277tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0278tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0279tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0280tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0281tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0282tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0283tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0284tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0285tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0286tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0287tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0288tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0289tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0290tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0291tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0292tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0293tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0294tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMoscheeinderFortezzaSultanIbrahimCamii__DSC0295tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0353tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0354tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0355tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0356tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0357tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0358tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0359tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0360tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0361tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0362tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0363tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0364tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0365tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0366tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0367tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0368tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0369tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0370tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0371tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0372tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0373tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0374tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0375tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0376tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0377tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0378tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0379tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0380tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0381tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0382tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0383tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0384tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0385tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0386tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0389tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0390tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0391tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0392tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0393tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0394tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0395tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0396tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0397tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0398tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0399tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0400tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0401tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0402tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0403tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0404tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0406tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0408tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0409tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0410tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0411tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0412tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0413tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0414tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0415tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBMyriokefalaPanagiaKirche__DSC0417tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0094tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0095tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0098tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0099tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0100tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0101tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0102tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0103tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0104tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0105tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0106tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0107tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0108tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0110tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0111tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0112tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0113tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0114tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0115tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0116tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0117tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0118tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0119tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0120tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0121tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0122tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0123tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0124tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0125tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0126tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0127tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0128tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0129tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0130tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0131tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0132tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0133tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0134tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0135tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0136tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0137tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0139tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0140tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0141tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0142tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0143tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0144tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0145tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0146tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0147tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0148tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0150tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0151tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPanagiaKeraKirchevonKritsa3Mai2013Fertig__DSC0152tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0301tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0302tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0303tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0304tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0305tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0306tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0307tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0308tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0309tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0310tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0311tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0312tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0313tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0314tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0315tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0316tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0317tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0318tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0319tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0320tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0321tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0323tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0324tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0325tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0326tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0327tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0328tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0329tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0330tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0331tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0333tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0334tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0335tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0336tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0337tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0338tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0339tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0340tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0341tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0342tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0343tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0344tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0345tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0346tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0347tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0348tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0349tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0350tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0351tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBPaschaNeraceMoscheeSultanIbrahimCamii__DSC0352tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBRimondiBrunnen__DSC0296tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBRimondiBrunnen__DSC0298tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBRimondiBrunnen__DSC0299tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBRimondiBrunnen__DSC0300tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBSanRoccoKapelle__DSC0491tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBSanRoccoKapelle__DSC0492tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBSanRoccoKapelle__DSC0493tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBSanRoccoKapelle__DSC0494tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBSanRoccoKapelle__DSC0495tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBSanRoccoKapelle__DSC0496tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBSanRoccoKapelle__DSC0497tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBSanRoccoKapelle__DSC0498tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBSanRoccoKapelle__DSC0499tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0418tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0419tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0420tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0421tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0422tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0423tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0424tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0425tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0426tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0427tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0428tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0429tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0430tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0431tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0432tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0433tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0434tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0435tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0436tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0437tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0438tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0439tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0440tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0441tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0442tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0443tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0444tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0445tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0446tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0447tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0448tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0449tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0450tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0451tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0452tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0453tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0454tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0455tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0456tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0457tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0458tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0459tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0460tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0461tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0462tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0463tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0464tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0465tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0466tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0467tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0468tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0469tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0470tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0471tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0472tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0473tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0474tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0475tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0476tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBStylosIoannisKirche__DSC0477tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0215tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0217tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0218tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0219tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0220tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0222tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0223tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0224tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0225tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0226tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0227tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0228tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0229tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0230tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0231tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0232tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0233tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0234tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0235tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0236tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0237tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0238tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0239tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0240tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0241tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0242tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0243tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0244tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0245tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0246tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0247tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0248tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0249tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0250tif -c fix_bag.json
./fix_bag.pl -fix_wrong_provenience_date DiFaBVeliPaschaMoscheeundTekkesi__DSC0251tif -c fix_bag.json

